---
- name: Install bash config
  ansible.builtin.copy:
    src: dotfiles/bash/bashrc
    dest: "/home/{{ ansible_user }}/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '600'
  when: bash|bool

- name: Install bash profile config
  ansible.builtin.copy:
    src: dotfiles/bash/bash_profile
    dest: "/home/{{ ansible_user }}/.bash_profile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '600'
  when: bash|bool

- name: Install bash config for root
  ansible.builtin.copy:
    src: dotfiles/bash/bashrc
    dest: "/root/.bashrc"
    owner: root
    group: root
    mode: '600'
  become: true
  when: bash|bool and bash_root|bool

- name: Install bash profile config for root
  ansible.builtin.copy:
    src: dotfiles/bash/bash_profile
    dest: "/root/.bash_profile"
    owner: root
    group: root
    mode: '600'
  become: true
  when: bash|bool and bash_root|bool
