---
- name: Include alacritty configuration
  ansible.builtin.include_tasks: alacritty.yml

- name: Include bash configuration
  ansible.builtin.include_tasks: bash.yml

- name: Include mako configuration
  ansible.builtin.include_tasks: mako.yml

- name: Include neovim configuration
  ansible.builtin.include_tasks: neovim.yml

- name: Include qutebrowser configuration
  ansible.builtin.include_tasks: qutebrowser.yml

- name: Include rust configuration
  ansible.builtin.include_tasks: rust.yml

- name: Include scripts
  ansible.builtin.include_tasks: scripts.yml

- name: Include sway configuration
  ansible.builtin.include_tasks: sway.yml

- name: Include syncthing configuration
  ansible.builtin.include_tasks: syncthing.yml

- name: Include tmux configuration
  ansible.builtin.include_tasks: tmux.yml

- name: Include weechat configuration
  ansible.builtin.include_tasks: weechat.yml

- name: Secure ownership recursively on home directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}"
    mode: "u=rwX,g-rwx,o-rwx"
    recurse: true
    follow: false
    modification_time: "preserve"
    access_time: "preserve"
