---
- include_tasks: alacritty.yml
- include_tasks: bash.yml
- include_tasks: neovim.yml
- include_tasks: sway.yml

- name: Secure ownership recursively on home directory
  file:
    path: "/home/{{ ansible_user }}"
    mode: "u=rwX,g-rwx,o-rwx"
    recurse: true
    follow: false
    modification_time: "preserve"
    access_time: "preserve"
