---
- name: Ensure ~/.config/mako exists
  file:
    path: "/home/{{ ansible_user }}/.config/mako"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  when: mako|bool

- name: Install mako configuration file
  copy:
    src: dotfiles/mako/config
    dest: "/home/{{ ansible_user }}/.config/mako/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: sway|bool
