---
- name: Ensure ~/.config/mako exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/mako"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '700'
  when: mako|bool

- name: Install mako configuration file
  ansible.builtin.copy:
    src: dotfiles/mako/config
    dest: "/home/{{ ansible_user }}/.config/mako/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '600'
  when: mako|bool
