---
- name: Ensure ~/.config/nvim exists
  file:
    path: "/home/{{ ansible_user }}/.config/nvim/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
    state: directory
  when: neovim|bool

- name: Install neovim configuration file
  copy:
    src: dotfiles/neovim/init.lua
    dest: "/home/{{ ansible_user }}/.config/nvim/init.lua"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: neovim|bool

- name: Install neovim lua directory
  synchronize:
    src: "dotfiles/neovim/lua"
    dest: "/home/{{ ansible_user }}/.config/nvim/"
  when: neovim|bool
