---
- name: Ensure ~/.config/nvim exists
  file:
    path: "/home/{{ ansible_user }}/.config/nvim/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
    state: directory
  with_items:
    - "pack/plugin/start"
  when: neovim|bool

- name: Install neovim ASCII art file
  copy:
    src: dotfiles/neovim/neovim
    dest: "/home/{{ ansible_user }}/.config/nvim/neovim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: neovim|bool

- name: Install neovim configuration file
  copy:
    src: dotfiles/neovim/init.lua
    dest: "/home/{{ ansible_user }}/.config/nvim/init.lua"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: neovim|bool
