---
- name: Ensure ~/.config/qutebrowser exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/qutebrowser"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '700'
  when: qutebrowser|bool

- name: Install qutebrowser configuration file
  ansible.builtin.copy:
    src: dotfiles/qutebrowser/config.py
    dest: "/home/{{ ansible_user }}/.config/qutebrowser/config.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '600'
  when: qutebrowser|bool
