---
- name: Ensure ~/.config/qutebrowser exists
  file:
    path: "/home/{{ ansible_user }}/.config/qutebrowser"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  when: qutebrowser|bool

- name: Install qutebrowser configuration file
  copy:
    src: dotfiles/qutebrowser/config.py
    dest: "/home/{{ ansible_user }}/.config/qutebrowser/config.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: qutebrowser|bool
