---
- name: Ensure ~/.bin exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.bin"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '700'
    state: directory
  when: scripts|bool

- name: Install user scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/.bin/{{ item | basename }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '700'
  loop: "{{ lookup('fileglob', 'files/scripts/bin/*', wantlist=True) }}"
  when: scripts|bool

- name: Ensure ~/.bin/snippets exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.bin/snippets"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '700'
    state: directory
  when: scripts|bool

- name: Install user snippets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/.bin/snippets/{{ item | basename }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '700'
  loop: "{{ lookup('fileglob', 'files/scripts/snippets/*', wantlist=True) }}"
  when: scripts|bool
