---
- name: Ensure ~/.config/sway exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/sway"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  when: sway|bool

- name: Install sway configuration file
  ansible.builtin.copy:
    src: dotfiles/sway/config
    dest: "/home/{{ ansible_user }}/.config/sway/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: sway|bool

- name: Ensure ~/.config/waybar exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/waybar"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  when: sway|bool

- name: Install waybar config
  ansible.builtin.copy:
    src: dotfiles/waybar/config
    dest: "/home/{{ ansible_user }}/.config/waybar/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: sway|bool

- name: Install waybar style sheet
  ansible.builtin.copy:
    src: dotfiles/waybar/style.css
    dest: "/home/{{ ansible_user }}/.config/waybar/style.css"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: sway|bool

- name: Install udev rules for backlight
  become: true
  ansible.builtin.copy:
    src: backlight.rules
    dest: /etc/udev/rules.d/90-backlight.rules
    owner: root
    group: root
    mode: 0644
  when: sway|bool
