---
- name: Start and enable the syncthing service in userspace
  ansible.builtin.systemd:
    name: syncthing
    scope: user
    enabled: true
    state: started
  when: syncthing|bool

- name: Ensure /var/lib/systemd/linger exists
  ansible.builtin.file:
    path: /var/lib/systemd/linger
    owner: root
    group: root
    mode: '755'
    state: directory
  become: true
  when: syncthing|bool

- name: Verify whether lingering is enabled for user
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ ansible_user }}"
  register: linger
  when: syncthing|bool

- name: Enable lingering for user
  ansible.builtin.command: loginctl enable-linger "{{ ansible_user }}"
  become: true
  changed_when: true
  when: syncthing|bool and not linger.stat.exists
