---
- name: Install tmux config
  ansible.builtin.copy:
    src: dotfiles/tmux/tmux.conf
    dest: "/home/{{ ansible_user }}/.tmux.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '600'
  when: tmux|bool
