---
- name: Install tmux config
  copy:
    src: tmux/tmux.conf
    dest: "/home/{{ ansible_user }}/.tmux.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: tmux|bool
